---
- hosts: all

  pre_tasks:

  - name: Setting facts
    when: "{{ item in inventory_hostname }}"
    ansible.builtin.set_fact:
      hostname:
         name: "{{ item }}"
    loop: "{{ groups['all'] }}"


  vars_files:
    - vars/main.yml 
    
  roles:
    - { role: gateway , when: "'h-gateway' in inventory_hostname" } 
    - { role: dhcp , when: "'h-dhcp' in inventory_hostname" }
    - { role: nodeApp }




  tasks:

    # - name: Run nodeApp tasks
    #   include_tasks: tasks/main.yml

    - name: debug
      debug:
        msg: "{{ ansible_facts.hostname.name}}"

    - name: Run DNS tasks
      when:  "{{ 'h-dns' in ansible_facts.hostname }}"
      include_tasks: tasks/main.yml

    # - name: Removing ens192
    #   when: "{{ 'h-dhcp' in inventory_hostname }}"
    #   community.general.nmcli:
    #     conn_name: ens192
    #     state: absent

    # - name: Removing ens192
    #   when: "{{ 'h-gateway' in inventory_hostname }}"
    #   community.general.nmcli:
    #     conn_name: ens192
    #     state: absent
      
    # - name: Removing ens192
    #   when: "{{ 'h-dns' in inventory_hostname }}"
    #   community.general.nmcli:
    #     conn_name: ens192
    #     state: absent
