---
- hosts: all

  pre_tasks:

  - name: Setting facts
    when: "{{ item in inventory_hostname }}"
    ansible.builtin.set_fact:
      target_url: "{{ hostvars[item].groups['all'][index -1] }}"
    loop: "{{ groups['all'] }}"
    loop_control:
      index_var: index

  vars_files:
    - vars/main.yml 
    
  roles:
    - { role: gateway , when: "'h-gateway' in inventory_hostname" } 
    - { role: dhcp , when: "'h-dhcp' in inventory_hostname" }
    - { role: nodeApp }

  tasks:
    - name: Debug
      debug: 
        msg: "{{ target_url }}"
    
    - name: Run DNS tasks
      when:  "{{ 'h-dns' in ansible_facts.hostname }}"
      include_tasks: tasks/main.yml


