---
- hosts: all

  pre_tasks:

  - name: Setting facts
    ansible.builtin.set_fact:
      hostname:
         name: "{{ item }}"
    loop: "{{ groups['all'] }}"


  # vars_files:
  #   - vars/main.yml 
    
  # roles:
  #   - { role: gateway , when: "'h-gateway-instance' in inventory_hostname" } 
  #   - { role: dhcp , when: "'h-dhcp-instance' in inventory_hostname" }
  #   - { role: nodeApp }




  tasks:


      - name: 
        debug:
          msg: "{{ hostname }}"

    # - name: Create hostnames loop
    #   user:
    #     name: "{{ item }}"
    #     state: present
    #   loop: "{{ hostvars }}"

    # - name: Run nodeApp tasks
    #   include_tasks: tasks/main.yml

    # - name: Run DNS tasks
    #   when:  "{{ 'h-dns-instance' in ansible_facts.hostname }}"
    #   include_tasks: tasks/main.yml

