---
- hosts: all

  pre_tasks:

  - name: Setting mac address facts
    ansible.builtin.set_fact:
      dhcp_macaddress: "{{hostvars['h-dhcp-instance'].ansible_ens224.macaddress}}" 

  vars_files:
    - vars/main.yml 
    
  roles:
    - { role: gateway , when: "'h-gateway-instance' in inventory_hostname" } 
    - { role: dhcp , when: "'h-dhcp-instance' in inventory_hostname" }
    - { role: nodeApp }




  tasks:

    # - name: Create hostnames loop
    #   user:
    #     name: "{{ item }}"
    #     state: present
    #   loop:
    #     - gateway 
    #     - dhcp 
    #     - dns 

    # - name: Run nodeApp tasks
    #   include_tasks: tasks/main.yml

    - name: Run DNS tasks
      when:  "{{ 'h-dns-instance' in ansible_facts.hostname }}"
      include_tasks: tasks/main.yml

