---
- hosts: all

  pre_tasks:

  - name: Setting facts
    when: "{{ item in inventory_hostname }}"
    ansible.builtin.set_fact:
      hostname:
         name: "{{ item }}"
    loop: "{{ groups['all'] }}"


  # vars_files:
  #   - vars/main.yml 
    
  # roles:
  #   - { role: gateway , when: "'h-gateway-instance' in inventory_hostname" } 
  #   - { role: dhcp , when: "'h-dhcp-instance' in inventory_hostname" }
  #   - { role: nodeApp }




  tasks:

    # - name: Run nodeApp tasks
    #   include_tasks: tasks/main.yml

    - name: debug
      debug:
        msg: "{{ ansible_facts.hostname | split('-') | second }}"

    - name: Run DNS tasks
      when:  "{{ 'h-dns-instance' in ansible_facts.hostname }}"
      include_tasks: tasks/main.yml

