---
- src: https://github.com/EAS-Harrison/ansible-dhcp-repo
  scm: git
  version: main
  name: dhcp

- src: https://github.com/EAS-Harrison/ansible-gateway-role
  scm: git
  version: main
  name: gateway