---
- src: https://github.com/EAS-Harrison/ansible-gateway-role
  scm: git
  version: multi
  name: gateway

- src: https://github.com/EAS-Harrison/ansible-dhcp-repo
  scm: git
  version: multi
  name: dhcp

- src: https://github.com/EAS-Harrison/ansible-dns-repo
  scm: git
  version: multi
  name: dns

- src: https://github.com/EAS-Harrison/ansible-nodeApp-repo
  scm: git
  version: multi
  name: nodeApp